"""The installed `<install>/bin/sv0c` launcher (NEX-060c).

Implements OD-009/CLI-017's installed-adapter-parity requirement
(`~/Documents/project-specs/sv0c-runtime-executable/SPEC.md` §11.1, §33.2):
per `sv0c/doc/native-executable-installed-command-design.md` (NEX-060a),
the installed `sv0c --emit=exe` command is a thin launcher forwarding
into the exact same, already-tested Python driver used by the workspace
adapter (`./scripts/sv0 native-compile`) -- not a new implementation, and
not a change to any sv0c compiler internals. `native_exe_cli.py` already
speaks the installed grammar (`--emit=exe` accepted, `--target=vm`/`.sv0b`
rejected per GOV-002/003), so this module needs no argv-translation logic
of its own: it only writes the launcher script and proves it behaves
identically to the workspace adapter for the same input.

Depends on `native_exe_installed_layout.build_install_layout` (NEX-060b)
for the installed tree shape (`<root>/scripts/native_exe_main.py`,
`<root>/sv0c/runtime/*`, `<root>/build/sv0-megatu-native`) the launcher
assumes.

Run `python3 scripts/native_exe_install_launcher.py --selftest` for the corpus.
"""

from __future__ import annotations

import os
import stat
import subprocess
import sys
import tempfile

from native_exe_installed_layout import build_install_layout

# Mirrors two existing precedents exactly, rather than inventing a third
# self-locating idiom: `scripts/sv0`'s own
# `ROOT="$(cd "$(dirname "$0")/.." && pwd)"`, and
# `scripts/build-sv0-megatu-native.sh`'s generated wrapper
# (`_HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"`). `bin/sv0c`
# lives one level below the install root (same as `scripts/sv0`), so its
# root is `dirname "$0"`'s parent, exactly like `scripts/sv0`'s own ROOT.
LAUNCHER_TEMPLATE = """#!/usr/bin/env bash
# Installed sv0c launcher (NEX-060c). Forwards argv unmodified into the
# native-executable driver -- native_exe_cli.py already speaks this exact
# grammar (--emit=exe accepted, --target=vm/.sv0b rejected). Generated by
# scripts/native_exe_install_launcher.py; do not hand-edit -- regenerate
# from an installed-layout build instead.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
exec python3 "$ROOT/scripts/native_exe_main.py" "$@"
"""


def write_sv0c_launcher(install_root: str) -> str:
    """Write `<install_root>/bin/sv0c`, executable, and return its path.

    Assumes `install_root` already has the `build_install_layout` shape
    (`<install_root>/scripts/native_exe_main.py` present) -- this function
    only writes the launcher script itself, it does not build the rest of
    the install tree (that's `build_install_layout`'s job, kept separate
    so a caller can regenerate just the launcher without re-copying the
    whole runtime bundle).
    """
    bin_dir = os.path.join(install_root, "bin")
    os.makedirs(bin_dir, exist_ok=True)
    launcher_path = os.path.join(bin_dir, "sv0c")
    with open(launcher_path, "w", encoding="utf-8") as f:
        f.write(LAUNCHER_TEMPLATE)
    st = os.stat(launcher_path)
    os.chmod(launcher_path, st.st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
    return launcher_path


def _selftest() -> int:
    from native_exe_build import DEFAULT_COMPILER_PATH

    failures: list[str] = []

    if not os.path.isfile(DEFAULT_COMPILER_PATH):
        print(f"native_exe_install_launcher selftest SKIP: {DEFAULT_COMPILER_PATH} not built")
        return 0

    with tempfile.TemporaryDirectory(prefix="sv0c launcher root ") as install_root:
        build_install_layout(install_root)
        launcher_path = write_sv0c_launcher(install_root)

        # Case 1: the launcher file exists, is executable, and its shebang
        # is intact (a plain string-content sanity check before relying on
        # actually executing it).
        if not os.path.isfile(launcher_path):
            failures.append("case1: launcher was not written")
        elif not os.access(launcher_path, os.X_OK):
            failures.append("case1: launcher is not executable")

        # Case 2: `sv0c --emit=exe hello.sv0 -o out` -- the literal
        # installed spelling from spec §25 -- runs end to end from the
        # launcher's own path (no PATH lookup, no cwd assumption) and
        # produces a real, runnable binary.
        src = os.path.join(install_root, "hello.sv0")
        with open(src, "w", encoding="utf-8") as f:
            f.write('fn main() -> i32 {\n    println("sv0c launcher works");\n    return 13;\n}\n')
        out = os.path.join(install_root, "hello_out")
        proc = subprocess.run(
            [launcher_path, "--emit=exe", "-o", out, src], capture_output=True, text=True
        )
        if proc.returncode != 0 or not os.path.isfile(out):
            failures.append(f"case2: launcher build failed: rc={proc.returncode} stderr={proc.stderr!r}")
        else:
            run_proc = subprocess.run([out], capture_output=True, text=True)
            if run_proc.returncode != 13 or "sv0c launcher works" not in run_proc.stdout:
                failures.append(
                    f"case2: launcher-built binary misbehaved: "
                    f"rc={run_proc.returncode} stdout={run_proc.stdout!r}"
                )

        # Case 3 (CLI-017's literal parity claim): the launcher's argv
        # grammar is not reinterpreted by this module at all -- it forwards
        # unmodified into the same native_exe_cli.py the workspace adapter
        # uses. Confirm this end to end via BEHAVIORAL parity (matching
        # NEX-051b's own dev-vs-release parity standard: exit code + stdout,
        # not raw bytes) between `./scripts/sv0 native-compile` and the
        # installed launcher, given the identical source. Raw bytes are
        # deliberately NOT compared here: the two builds necessarily embed
        # different absolute runtime-source paths in `-g` debug info (one
        # from the real repo, one from the installed copy at a different
        # path) -- a real, expected difference independent of the driver,
        # not the same "known, single-root-cause" divergence NEX-053a's
        # UUID classifier exists to explain.
        this_dir = os.path.dirname(os.path.abspath(__file__))
        root_dir = os.path.normpath(os.path.join(this_dir, ".."))
        workspace_out = os.path.join(install_root, "workspace_out")
        workspace_proc = subprocess.run(
            [os.path.join(root_dir, "scripts", "sv0"), "native-compile", "-o", workspace_out, src],
            capture_output=True,
            text=True,
        )
        if workspace_proc.returncode != 0 or not os.path.isfile(workspace_out):
            failures.append(f"case3: workspace-adapter build failed: rc={workspace_proc.returncode}")
        elif not os.path.isfile(out):
            failures.append("case3: skipped -- case2's launcher build did not produce an output binary")
        else:
            launcher_run = subprocess.run([out], capture_output=True, text=True)
            workspace_run = subprocess.run([workspace_out], capture_output=True, text=True)
            if (launcher_run.returncode, launcher_run.stdout) != (workspace_run.returncode, workspace_run.stdout):
                failures.append(
                    "case3: installed launcher and workspace adapter behaved differently for "
                    f"the same source: launcher={launcher_run.returncode, launcher_run.stdout!r} "
                    f"workspace={workspace_run.returncode, workspace_run.stdout!r}"
                )

        # Case 4 (GOV-002/003 bytecode isolation, unchanged by this
        # module): --target=vm is still rejected -- proves argv really is
        # forwarded, not silently reinterpreted or loosened.
        bogus_proc = subprocess.run(
            [launcher_path, "--target=vm", src], capture_output=True, text=True
        )
        if bogus_proc.returncode != 2:
            failures.append(f"case4: expected --target=vm rejection (exit 2), got {bogus_proc.returncode}")

    if failures:
        for f in failures:
            print(f"native_exe_install_launcher selftest FAIL: {f}")
        return 1

    print("native_exe_install_launcher: selftest OK (4 cases)")
    return 0


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        raise SystemExit(_selftest())
    print("native_exe_install_launcher: library module; use --selftest", file=sys.stderr)
    raise SystemExit(2)
